indicators:
  QA:
    listeners:
      - merge:
          name: old ESB API test feature branches
          max_age_weeks: 104
          # git clone URL
          repo: ssh://git@stash.aws.medibank.local:7999/medi_corp/esb-api-tests.git
          # 'master' branch to check merges against
          master: origin/master
          # 'grace' period-- any matching branch younger than this is not checked
          stale_days: 30
          name_patterns:
            - .*/feature/.+
      - merge:
          name: CI-Monitor old feature branches check
          max_age_weeks: 200
          location: scratch/repos
          repo: ssh://git@stash.aws.medibank.local:7999/medi_corp/ci-monitor.git
          master: origin/master
          stale_days: 30
          name_patterns:
            - .*/feature/.+
      - merge:
          name: BDD UI Framework old feature files
          max_age_weeks: 200
          repo: ssh://git@stash.aws.medibank.local:7999/medi_corp/bdd-features.git
          master: origin/develop
          stale_days: 30
          name_patterns:
            - .*/feature/.+
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav
schedule:
  - daily at 10:15
