heartbeat_secs: 10
errorheartbeat_secs: 10
schedule:
    - every heartbeat
logging:
    console: warning
    fileRotator: info
proxies:
    http: http://ausydisa02.au.imckesson.com:8080
    https: http://ausydisa02.au.imckesson.com:8080
states:
  # numeric string as keys because ostruct currently can't handle numerics in key position
  - alltestspassed
  - failures
  - commserror
  - commserrorandfailures
  - internalexception
severities:
  warnings: [commserrorandfailures, failures, commserror]
  errors: [internalexception]
lights:
  lamppatterns:
    failures: [red]
    alltestspassed: [green]
    blank: [alloff]
    internalexception: [red, yellow, green]
    commserror: [yellow]
    commserrorandfailures: [red, yellow]
    changestate: [red, green]
  blinktime_secs: 0.1