  RetailPROD:
    sitemap:
      schedule:
        - 08:30AM
        - 12:00PM
        - 04:30PM
      files:
        prod-aem: https://www.medibank.com.au/sitemap-retail.xml
        prod-legacy: https://www.medibank.com.au/sitemap-legacy.xml
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav

  RetailDEV:
    testables:
#      - sitemap:
#          name: Legacy.NET
#          interval_mins: 20
#          file: http://dev-aem.medibank.local/sitemap-legacy.xml
#      - sitemap:
#          name: AEM
#          interval_mins: 20
#          file: http://dev-aem.medibank.local/sitemap-retail.xml
      - merge:
          name: OMS
          max_age_weeks: 12
          location: scratch/repos
          repos:
            'api-gateway': ssh://git@stash.aws.medibank.local:7999/oms/api-gateway.git
            'integration-services': ssh://git@stash.aws.medibank.local:7999/medi_corp/integration-services.git
            'member-services-aem': ssh://git@stash.aws.medibank.local:7999/oms/member-services-aem.git
            'aem-core': ssh://git@stash.aws.medibank.local:7999/medi_corp/aem-core.git
          master: origin/master
          stale_days: 3
          name_patterns:
            - .*/release/.+
            - .*/hotfix/.+
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav