indicators:
  OMS:
    listeners:
      - bamboo:
          name: DEV01
          template: https://bamboo.digidev-aws.medibank.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            API tests: MDAL-AGAT
            Jasmine tests: MDO-MSA
      - bamboo:
          name: WSDLs
          template: https://bamboo.digidev-aws.medibank.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            ESB API tests: MDAL-ESS
      - sitemap:
          name: Legacy
          file: http://dev-aem.medibank.local/sitemap-legacy.xml
          schedule:
            - daily at 09:00
            - daily at 12:00
            - daily at 15:00
      - sitemap:
          name: AEM
          file: http://dev-aem.medibank.local/sitemap-retail.xml
          schedule:
            - daily at 10:00
            - daily at 13:00
            - daily at 16:00
      - merge:
          name: API Gateway
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.medibank.local:7999/oms/api-gateway.git
          master: origin/master
          stale_days: 3
          name_patterns:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:00
      - merge:
          name: Integration Services
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.medibank.local:7999/medi_corp/integration-services.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:05
      - merge:
          name: Member Services AEM
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.medibank.local:7999/oms/member-services-aem.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - every heartbeat
      - merge:
          name: AEM Core
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.medibank.local:7999/medi_corp/aem-core.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:10
    trafficlight:
      id: 901880
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav
defaults:
  heartbeat_secs: 15
  errorheartbeat_secs: 10
  schedule:
    - every heartbeat
logging:
    console: warning
    fileRotator: info
proxies:
    http: http://ausydisa02.au.imckesson.com:8080
    https: http://ausydisa02.au.imckesson.com:8080
states:
  # numeric strings as keys because ostruct currently can't handle numerics in key position
  - alltestspassed
  - failures
  - commserror
  - commserrorandfailures
  - internalexception
severities:
  warnings: [commserrorandfailures, failures, commserror]
  errors: [internalexception]

lights:
  lamppatterns:
    failures: [red]
    alltestspassed: [green]
    blank: [alloff]
    internalexception: [red, yellow, green]
    commserror: [yellow]
    commserrorandfailures: [red, yellow]
    changestate: [red, green]
  blinktime_secs: 0.1