indicators:
  OMS:
    listeners:
      - bamboo:
          name: DEV01
          template: https://bamboo.digidev-aws.someorg.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            API tests: MDAL-AGAT
            Jasmine tests: MDO-MSA
#      - bamboo:
#          name: WSDLs
#          template: https://bamboo.digidev-aws.someorg.local/rest/api/latest/result/{tag}/latest.json
#          tasks:
#            ESB API tests: MDAL-ESS
      - merge:
          name: API Gateway
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.someorg.local:7999/oms/api-gateway.git
          master: origin/master
          stale_days: 3
          name_patterns:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:00
      - merge:
          name: Integration Services
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.someorg.local:7999/medi_corp/integration-services.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:05
      - merge:
          name: Member Services AEM
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.someorg.local:7999/oms/member-services-aem.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:10
      - merge:
          name: AEM Core
          max_age_weeks: 12
          location: scratch/repos
          repo: ssh://git@stash.aws.someorg.local:7999/medi_corp/aem-core.git
          master: origin/master
          stale_days: 3
          branches:
            - .*/release/.+
            - .*/hotfix/.+
          schedule:
            - daily at 10:10
    trafficlight:
      id: 901880
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav