indicators:
  RetailCorp:
    listeners:
      - bamboo:
          name: Retail DEV
          template: https://bamboo.digidev-aws.someorg.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            dev-corporate: MDCW-RCWAT38
            dev-elevate:  MDCW-RCWAT39
            dev-inc: MDCW-RCWAT40
            dev-retail: MDCW-RCWAT41
            redBuildSmoke: MDCW-RCWAT88
      - sitemap:
          name: Legacy
          file: http://dev-aem.someorg.local/sitemap-legacy.xml
          schedule:
            - daily at 09:00
            - daily at 12:00
            - daily at 15:00
      - sitemap:
          name: DEV-AEM
          file: http://dev-aem.someorg.local/sitemap-retail.xml
          schedule:
            - daily at 09:05
            - daily at 14:00
            - daily at 16:00
      - sitemap:
          name: Production Retail
          file: http://www.someorg.com.au/sitemap-retail.xml
          schedule:
            - daily at 9:16
      - sitemap:
          name: Production Legacy
          file: http://www.someorg.com.au/sitemap-legacy.xml
          schedule:
            - every heartbeat
    trafficlight:
      id: 901880
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav
schedule:
  - always
