indicators:
  OMS:
    monitoring:
      - bamboo:
          name: DEV01
          template: https://bamboo.digidev-aws.medibank.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            API tests: MDAL-AGAT
            Jasmine unit tests: MDO-MSA
      - bamboo:
          name: WSDLs
          template: https://bamboo.digidev-aws.medibank.local/rest/api/latest/result/{tag}/latest.json
          tasks:
            ESB API tests: MDAL-ESS
    schedule:
      - always
    trafficlight:
      id: 901880
    sounds:
      failures: alarm_beep.wav
      greenbuild: applause.wav